name: Deploy (Production)

on:
  push:
    branches:
      - dev

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: read
      deployments: write
    environment:
      name: Production
      url: https://huling.org/

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Use Volta
        uses: volta-cli/action@v1

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: ./src/.vitepress/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
